name: Azure Bicep Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Validate and Deploy Bicep to Azure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Bicep - Validate Template
      run: |
        az bicep build --file main.bicep
        az deployment group validate \
          --resource-group rg-cs5304-shahzebfaisal5649 \
          --template-file main.bicep

    # Optional: Uncomment below to enable automatic deployment
    # - name: Azure Bicep - Deploy Template
    #   run: |
    #     az deployment group create \
    #       --resource-group rg-cs5304-shahzebfaisal5649 \
    #       --template-file main.bicep
